In [1]:
import numpy as np


In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[5,4,6],[9,8,7],[4,0,6]]
my_matrix

[[5, 4, 6], [9, 8, 7], [4, 0, 6]]

In [6]:
np.array(my_matrix)

array([[5, 4, 6],
       [9, 8, 7],
       [4, 0, 6]])

In [7]:
# ARANGE
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
np.arange(0,15,3)

array([ 0,  3,  6,  9, 12])

In [9]:
np.arange(0,15,5)

array([ 0,  5, 10])

In [10]:
# ZEROS  AND ONES
np.zeros(4)

array([0., 0., 0., 0.])

In [12]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.zeros((6,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
#  LINSPACE   (this is parts of data)
np.linspace(0,12,2)

array([ 0., 12.])

In [19]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [20]:
np.linspace(0,12,4)   

array([ 0.,  4.,  8., 12.])

In [21]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [22]:
# eye 
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
# RANDOM
np.random.rand(2)

array([0.95604961, 0.66014791])

In [24]:
np.random.rand(2)

array([0.9673343 , 0.23281953])

In [25]:
np.random.rand(2,3)

array([[0.73312598, 0.70645735, 0.78121927],
       [0.5328421 , 0.82444707, 0.52015061]])

In [26]:
# RANDN
np.random.randn(2)

array([1.11136761, 0.03474763])

In [27]:
np.random.randn(2)

array([ 1.125654  , -0.85316927])

In [28]:
np.random.randint(2)

1

In [29]:
np.random.randint(1,50)

13

In [30]:
np.random.randint(1,50,12)

array([18, 44, 28, 37, 10, 39, 18,  2, 35,  5, 17, 46])

In [35]:
np.random.seed(32)
np.random.rand(2)

array([0.85888927, 0.37271115])

In [34]:
np.random.seed(32)
np.random.rand(2)

array([0.85888927, 0.37271115])

In [36]:
np.random.seed(54)
np.random.rand(4)

array([0.42018297, 0.3632395 , 0.18487669, 0.51828273])

In [37]:
np.random.seed(54)
np.random.rand(4)

array([0.42018297, 0.3632395 , 0.18487669, 0.51828273])

In [38]:
num = np.arange(34)
num

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [40]:
rannum = np.random.randint(0,34,10)
rannum

array([25, 23,  3,  1, 18, 11, 26, 24,  7, 18])

In [43]:
# RESHAPE
re = np.arange(16)
re

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [45]:
ranre = np.random.randint(0,16,4)
ranre

array([14,  3,  5,  7])

In [46]:
re.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [47]:
rannum

array([25, 23,  3,  1, 18, 11, 26, 24,  7, 18])

In [49]:
rannum.max()

26

In [50]:
rannum.min()

1

In [51]:
rannum.argmax()

6

In [52]:
rannum.argmin()

3